// Faculdade/2º periodo/N3/livros-react/src/LivroLista.js
import React, { useState, useEffect, useMemo } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditoras from './controle/ControleEditoras';

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  const controleLivro = useMemo(() => new ControleLivros(), []); // Utilize useMemo para memorizar o objeto controleLivro
  const controleEditora = useMemo(() => new ControleEditoras(), []); // Utilize useMemo para memorizar o objeto controleEditora

  useEffect(() => {
    const carregarLivros = async () => {
      const livros = await controleLivro.obterLivros();
      setLivros(livros);
      setCarregado(true);
    };

    if (!carregado) {
      carregarLivros();
    }
  }, [carregado, controleLivro]);

  const excluirLivro = (codigo) => {
    controleLivro.excluir(codigo);
    setCarregado(false); // Força o redesenho da página após a exclusão
  };

  const LinhaLivro = ({ livro }) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    const handleExcluirLivro = () => {
      excluirLivro(livro.codigo);
    };

    return (
      <tr>
        <td>
          <button onClick={handleExcluirLivro}>Excluir</button>
        </td>
        <td>{livro.codigo}</td>
        <td>{livro.titulo}</td>
        <td>{livro.resumo}</td>
        <td>{nomeEditora}</td>
        <td>
          <ul>
            {livro.autores.map((autor, index) => (
              <li key={index}>{autor}</li>
            ))}
          </ul>
        </td>
      </tr>
    );
  };

  return (
    <main>
      <h1>Lista de Livros</h1>
      <table>
        <thead>
          <tr>
            <th>Ações</th>
            <th>Código</th>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <LinhaLivro key={livro.codigo} livro={livro} />
          ))}
        </tbody>
      </table>
    </main>
  );
};

export default LivroLista;

// Faculdade/2º periodo/N4/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  template: `
    <h2>Editoras:</h2>
    <ul>
      <li *ngFor="let editora of editoras">{{ editora.nome }}</li>
    </ul>
    <h2>Livros:</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Resumo</th>
          <th>Autores</th>
          <th>Editora</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}</td>
          <td>{{ livro.resumo }}</td>
          <td>{{ livro.autores.join(', ') }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  `
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir(codigo: number): void {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main class="container">
    <h1>Livros</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Resumo</th>
          <th>Autores</th>
          <th>Editora</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}</td>
          <td>{{ livro.resumo }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
